/* PLATAFORMA DE PERGUNTAS E RESPOSTAS */

-- CONCEITUAL

-- DESENVOLVER UMA PLATAFORMA DE PERGUNTAS E RESPOSTAS COM AUTENTICAÇÃO DE USUARIOS.

-- REGRAS DE NEGOCIOS: TODO USUARIO PARA ACESSAR O SISTEMA DEVE ESTAR AUTENTICADO, TODA SENHA DEVE TER NO MINIMO/MAXIMO 8 CARACTERES, NÃO PODE HAVER NENHUM EMAIL IGUAL PARA FACILITAÇÃO DE ENVIO DE MALAS DIRETAS AO USUARIO.

/* ENTIDADE USUARIO */
NOME CARACTER NÃO NULO
IDADE INT NÃO NULO
SEXO ENUM NÃO NULO
CIDADE ENUM NÃO NULO
EMAIL CARACTER NÃO NULO
SENHA CARACTER NÃO NULO 

/* ENTIDADE PERGUNTA */
TITULO CARACTER NÃO NULO
DESCRIÇÃO CARACTER NÃO NULO 

/* ENTIDADE RESPOSTA */
CORPO CARACTER NÃO NULO


/* MODELAGEM LOGICA NO MYSQL WORKBEACH */


/* MODELAGEM FISICA */

CREATE DATABASE PERGRESP;

USE PERGRESP;

CREATE TABLE USER(
  IDUSER INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  AGE CHAR(3) NOT NULL,
  SEX ENUM('M','F') NOT NULL,
  CITY CHAR(2) NOT NULL,
  EMAIL VARCHAR(100) UNIQUE NOT NULL,
  PASSWORD CHAR(8) NOT NULL
);

CREATE TABLE QUESTION(
  IDQUESTION INT PRIMARY KEY AUTO_INCREMENT,
  TITLE VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  ID_USER INT NOT NULL,
  FOREIGN KEY(ID_USER)
  REFERENCES USER(IDUSER)
);

CREATE TABLE ANSWER(
  IDANSWER INT PRIMARY KEY AUTO_INCREMENT,
  BODY VARCHAR(255) NOT NULL,
  ID_USER INT NOT NULL,
  ID_QUESTION INT NOT NULL,
  FOREIGN KEY(ID_USER) REFERENCES USER(IDUSER),
  FOREIGN KEY(ID_QUESTION) REFERENCES QUESTION(IDQUESTION)
);

/* TESTES DE BANCO */

/* TESTES DE INSERÇÃO DE USUARIOS */
INSERT INTO USER VALUES(NULL,'ANTONIO','20','M','RJ','ANTONIO@GMAIL.COM','12345678');
INSERT INTO USER VALUES(NULL,'PAULA','35','F','SP','PAULA@GMAIL.COM','12345678');
INSERT INTO USER VALUES(NULL,'JOAO','47','M','CE','JOAO@GMAIL.COM','12345678');
INSERT INTO USER VALUES(NULL,'ROBERTO','16','M','MT','ROBERTO@GMAIL.COM','12345678');
INSERT INTO USER VALUES(NULL,'GIOVANA','29','F','MG','GIOVANA@GMAIL.COM','12345678');


/* TESTES DE INSERÇÃO DE PERGUNTAS */
INSERT INTO QUESTION VALUES(NULL,'VALE A PENA APRENDER GIT?','PESSOAL QUERIA TIRAR UMA DUVIDA, VALE APENA APRENDER GIT?', 6);
INSERT INTO QUESTION VALUES(NULL,'MYSQL E BOM?','VALE A PENA APRENDER MYSQL?', 8);
INSERT INTO QUESTION VALUES(NULL,'PHP VALE A PENA?','PHP E BOM?', 1);
INSERT INTO QUESTION VALUES(NULL,'E NECESSARIO GRADUAÇÃO PARA ENTRAR MA AREA?','PESSOAL QUERIA TIRAR UMA DUVIDA, PRECISA DE FACULDADE PRA ENTRAR?', 7);


/* TESTES DE INSERÇÃO DE RESPOSTAS */
INSERT INTO ANSWER VALUES(NULL,'A PARTIR DA VERSÃO 8 FICOU OTIMO',8,3);







/* QUERYS */

SELECT U.NAME, U.EMAIL, Q.TITLE, A.BODY
FROM USER AS U
INNER JOIN QUESTION AS Q
ON U.IDUSER = Q.ID_USER
INNER JOIN ANSWER AS A
ON U.IDUSER = A.ID_USER;


SELECT NAME, EMAIL, TITLE, DESCRIPTION
FROM USER
INNER JOIN QUESTION
ON IDUSER = ID_USER
ORDER BY 2;